job_name: resnet18_pred
verision: 1.0.0
seed: 18

model:
  name: ResNet18
  params: 
    freeze_backbone: True
  threshold: 0.5
  weight: results\resnet18_train_1.0.0_2023-10-15_14-31-40Z\epoch_30.pth

data:
  geojson_path: ./data/raw/pred.geojson
  collections: sentinel-2-l2a
  datetime: 2022-01-01/2022-12-30
  band: visual
  patch_size: [150, 150]
  overlap: [0.25, 0.25]
  transform:
    - name: to_tensor
      params: {}
    - name: resize
      params:
        size: [224, 224]
    - name: normalize
      params:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
